version: '3'
services:
  neo4j:
    image: neo4j:latest
    hostname: neo4jServer
    volumes:
     - ./data/neo4j:/data           # 器内的数据目录挂载到宿主机的对应目录下
     - ./logs/neo4j:/logs              #挂载日志目录
     - ./conf:/var/lib/neo4j/conf      #挂载配置目录
     - ./import:/var/lib/neo4j/import  #挂载数据导入目录
    environment:
     - NEO4J_AUTH=neo4j/DCchengding2003         #设定数据库的名字的访问密码
    ports:
      - "7474:7474"                    #映射容器的端口号到宿主机的端口号
      - "7687:7687"
    restart: always